# Sentence Transformer

- Try BERT instead of SBERT
- Try to find a different SBERT model that's designed for HR
- Replace human resources with hr and try stemming
- Try FastText model
- Look up markov chain monte carlo
- Try alternatives to cosine similarity - BERT has in inbuilt one?

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.stem import PorterStemmer

In [33]:
data = pd.read_csv('../data/potential_talents_cleaned.csv')

In [34]:
data.head()

,id,job_title,location,connection,fit,job_title_stem
0,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,2019 c t bauer colleg of busi graduat magna cu...
1,2,native english teacher at epik english progra...,Kanada,500+,NaN,nativ english teacher at epik english program ...
2,3,aspiring hr professional,"Raleigh-Durham, North Carolina Area",44,NaN,aspir hr profession
3,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,peopl develop coordin at ryan
4,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,advisori board member at celal bayar univers

In [40]:
# choosing sentence transformer model to use
model = SentenceTransformer('all-MiniLM-L6-v2')

# creating embeddings of the target job title
stemmer = PorterStemmer()
target_title = 'aspiring hr'
target_stem = ' '.join(
    stemmer.stem(word)
    for word in target_title.split()
    )
target_embedding = model.encode([target_stem])

# creating embeddings of the words in the stemmed job titles
job_embeddings = model.encode(data['job_title_stem'].to_list())

# list different types of similarity scorers
similarity_scorers = ['cosine', 'dot', 'euclidean', 'manhattan']

# using each scorer to assess the similarities
for scorer in similarity_scorers:
    model.similarity_fn_name = scorer
    similarities = model.similarity(target_embedding, job_embeddings).flatten()
    data[f'{scorer}_similarity'] = similarities
    data[f'{scorer}_rank'] = (
        data[f'{scorer}_similarity']
        .rank(ascending=False, method='min')
        .astype(int)
    )

# display results
data = data.sort_values(by='cosine_rank', ascending=False).reset_index(drop=True)
data[['job_title', 'job_title_stem', 'cosine_rank', 'dot_rank', 'euclidean_rank', 'manhattan_rank']]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

,job_title,job_title_stem,cosine_rank,dot_rank,euclidean_rank,manhattan_rank
0,always set them up for success,alway set them up for success,53,53,53,50
1,people development coordinator at ryan,peopl develop coordin at ryan,52,52,52,53
2,bachelor of science in biology from victoria u...,bachelor of scienc in biolog from victoria uni...,51,51,51,52
3,native english teacher at epik english progra...,nativ english teacher at epik english program ...,50,50,50,51
4,business intelligence and analytics at travelers,busi intellig and analyt at travel,49,49,49,49
5,student at westfield state university,student at westfield state univers,48,48,48,44
6,rrp brand portfolio executive at jti japan to...,rrp brand portfolio execut at jti japan tobacc...,47,47,47,47
7,lead official at western illinois university,lead offici at western illinoi univers,46,46,46,48
8,information systems specialist and programmer ...,inform system specialist and programm with a l...,45,45,45,43
9,undergraduate research assistant at styczynski...,undergradu research assist at styczynski lab,44,44,44,45
10,student at indiana university kokomo busines...,student at indiana univers kokomo busi manag r...,43,43,43,42
11,advisory board member at celal bayar university,advisori board member at celal bayar univers,42,42,42,37
12,director of administration at excellence logging,director of administr at excel log,41,41,41,46
13,admissions representative at community medical...,admiss repres at commun medic center long beach,40,40,40,38
14,junior mes engineer information systems,junior me engin inform system,39,39,39,41
15,student,student,38,38,38,36
16,seeking employment opportunities within custom...,seek employ opportun within custom servic or p...,37,37,37,40
17,seeking human resources opportunities open t...,seek human resourc opportun open to travel and...,36,36,36,35
18,student at chapman university,student at chapman univers,35,35,35,39
19,hr coordinator at intercontinental buckhead at...,hr coordin at intercontinent buckhead atlanta,34,34,34,33
20,svp chro marketing communications csr off...,svp chro market commun csr offic engi houston ...,33,33,33,34
21,director of hr north america groupe beneteau,director of hr north america group beneteau,32,32,32,32
22,hr professional for the world leader in gis so...,hr profession for the world leader in gi softwar,31,31,31,30
23,hr generalist at scottmadden inc,hr generalist at scottmadden inc,30,30,30,25
24,hr manager at endemol shine north america,hr manag at endemol shine north america,29,29,29,28
25,hr \nconflict management \npolicies procedur...,hr conflict manag polici procedur talent manag...,28,28,28,29
26,director hr at ey,director hr at ey,27,27,27,31
27,hr generalist at loparex,hr generalist at loparex,26,26,26,27
28,senior hr business partner at heil environmental,senior hr busi partner at heil environment,25,25,25,26
29,hr staffing and recruiting professional,hr staf and recruit profession,24,24,24,24
30,nortia staffing is seeking hr payroll admin...,nortia staf is seek hr payrol administr profes...,23,23,23,23
31,hr generalist at schwan s,hr generalist at schwan s,22,22,22,22
32,retired army national guard recruiter office ...,retir armi nation guard recruit offic manag se...,21,21,21,19
33,hr management major,hr manag major,20,20,20,20
34,hr specialist at luxottica,hr specialist at luxottica,19,19,19,18
35,seeking hr hris and generalist positions,seek hr hri and generalist posit,18,18,18,17
36,2019 c t bauer college of business graduate ...,2019 c t bauer colleg of busi graduat magna cu...,17,17,17,21
37,hr senior specialist,hr senior specialist,16,16,16,16
38,seeking hr position,seek hr posit,15,15,15,12
39,hr professional,hr profession,14,14,14,15
40,aspiring hr professional passionate about he...,aspir hr profession passion about help to crea...,13,13,13,14
41,aspiring hr manager graduating may 2020 se...,aspir hr manag graduat may 2020 seek an entri ...,12,12,12,11
42,student at humber college and aspiring hr gene...,student at humber colleg and aspir hr generalist,11,11,11,13
43,experienced retail manager and aspiring hr pro...,experienc retail manag and aspir hr profession,10,10,10,10
44,aspiring hr management student seeking an inte...,aspir hr manag student seek an internship,9,9,9,8
45,seeking hr opportunities,seek hr opportun,8,8,8,9
46,business management major and aspiring hr manager,busi manag major and aspir hr manag,7,7,7,7
47,aspiring hr manager seeking internship in hr,aspir hr manag seek internship in hr,6,6,6,6
48,liberal arts major aspiring hr analyst,liber art major aspir hr analyst,5,5,5,5
49,aspiring hr professional an energetic and te...,aspir hr profession an energet and team focus ...,4,4,4,4
50,aspiring hr professional,aspir hr profession,2,2,2,2
51,aspiring hr professional,aspir hr profession,2,2,2,2
52,aspiring hr specialist,aspir hr specialist,1,1,1,1