# Sentence Transformer

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
data = pd.read_csv('../data/potential_talents_cleaned.csv')

In [7]:
data.head()

,id,job_title,location,connection,fit
0,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN
1,2,native english teacher at epik english progra...,Kanada,500+,NaN
2,3,aspiring human resources professional,"Raleigh-Durham, North Carolina Area",44,NaN
3,4,people development coordinator at ryan,"Denton, Texas",500+,NaN
4,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN

In [9]:
model = SentenceTransformer('all-MiniLM-L6-v2')

job_embeddings = model.encode(data['job_title'].to_list())

target_title = 'aspiring human resources'
target_embedding = model.encode([target_title])

similarities = cosine_similarity(
    target_embedding,
    job_embeddings
).flatten()

data['similarity'] = similarities

data = data.sort_values(by='similarity', ascending=False).reset_index(drop=True)

data

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

,id,job_title,location,connection,fit,similarity
0,3,aspiring human resources professional,"Raleigh-Durham, North Carolina Area",44,NaN,0.949807
1,97,aspiring human resources professional,"Kokomo, Indiana Area",71,NaN,0.949807
2,6,aspiring human resources specialist,Greater New York City Area,1,NaN,0.928035
3,99,seeking human resources position,"Las Vegas, Nevada Area",48,NaN,0.808784
4,28,seeking human resources opportunities,"Chicago, Illinois",390,NaN,0.799641
5,74,human resources professional,Greater Boston Area,16,NaN,0.794648
6,82,aspiring human resources professional an ene...,"Austin, Texas Area",174,NaN,0.776667
7,7,student at humber college and aspiring human r...,Kanada,61,NaN,0.757810
8,73,aspiring human resources manager seeking inte...,"Houston, Texas Area",7,NaN,0.747702
9,10,seeking human resources hris and generalist po...,Greater Philadelphia Area,500+,NaN,0.744711
10,67,human resources staffing and recruiting profe...,"Jackson, Mississippi Area",500+,NaN,0.734097
11,88,human resources management major,"Milpitas, California",18,NaN,0.726044
12,72,business management major and aspiring human r...,"Monroe, Louisiana Area",5,NaN,0.724114
13,27,aspiring human resources management student se...,"Houston, Texas Area",500+,NaN,0.720099
14,100,aspiring human resources manager graduating ...,"Cape Girardeau, Missouri",103,NaN,0.716278
15,66,experienced retail manager and aspiring human ...,"Austin, Texas Area",57,NaN,0.696065
16,79,liberal arts major aspiring human resources a...,"Baton Rouge, Louisiana Area",7,NaN,0.692124
17,76,aspiring human resources professional passio...,"New York, New York",212,NaN,0.686031
18,78,human resources generalist at schwan s,Amerika Birleşik Devletleri,500+,NaN,0.629672
19,68,human resources specialist at luxottica,Greater New York City Area,500+,NaN,0.622302
20,101,human resources generalist at loparex,"Raleigh-Durham, North Carolina Area",500+,NaN,0.603002
21,71,human resources generalist at scottmadden inc,"Raleigh-Durham, North Carolina Area",500+,NaN,0.598971
22,13,human resources coordinator at intercontinenta...,"Atlanta, Georgia",500+,NaN,0.595789
23,89,director human resources at ey,Greater Atlanta Area,349,NaN,0.571969
24,84,human resources professional for the world lea...,"Highland, California",50,NaN,0.565377
25,94,seeking human resources opportunities open t...,Amerika Birleşik Devletleri,415,NaN,0.564194
26,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,0.533774
27,69,director of human resources north america gro...,"Greater Grand Rapids, Michigan Area",500+,NaN,0.530981
28,70,retired army national guard recruiter office ...,"Virginia Beach, Virginia",82,NaN,0.521934
29,8,hr senior specialist,San Francisco Bay Area,500+,NaN,0.503456
30,77,human resources \nconflict management \npolici...,Dallas/Fort Worth Area,409,NaN,0.476708
31,81,senior human resources business partner at hei...,"Chattanooga, Tennessee Area",455,NaN,0.467560
32,83,hr manager at endemol shine north america,"Los Angeles, California",268,NaN,0.442391
33,86,information systems specialist and programmer ...,"Gaithersburg, Maryland",4,NaN,0.395006
34,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,0.380222
35,90,undergraduate research assistant at styczynski...,Greater Atlanta Area,155,NaN,0.369043
36,75,nortia staffing is seeking human resources pa...,"San Jose, California",500+,NaN,0.365747
37,11,student at chapman university,"Lake Forest, California",2,NaN,0.351657
38,92,seeking employment opportunities within custom...,"Torrance, California",64,NaN,0.341554
39,96,student at indiana university kokomo busines...,"Lafayette, Indiana",19,NaN,0.333863
40,80,junior mes engineer information systems,"Myrtle Beach, South Carolina Area",52,NaN,0.326926
41,95,student at westfield state university,"Bridgewater, Massachusetts",57,NaN,0.318234
42,91,lead official at western illinois university,Greater Chicago Area,39,NaN,0.275150
43,104,director of administration at excellence logging,"Katy, Texas",500+,NaN,0.275140
44,12,svp chro marketing communications csr off...,"Houston, Texas Area",500+,NaN,0.262039
45,98,student,"Houston, Texas Area",4,NaN,0.238388
46,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,0.230512
47,87,bachelor of science in biology from victoria u...,"Baltimore, Maryland",40,NaN,0.222139
48,2,native english teacher at epik english progra...,Kanada,500+,NaN,0.211303
49,93,admissions representative at community medical...,"Long Beach, California",9,NaN,0.161050
50,103,always set them up for success,Greater Los Angeles Area,500+,NaN,0.148272
51,85,rrp brand portfolio executive at jti japan to...,Greater Philadelphia Area,500+,NaN,0.112013
52,102,business intelligence and analytics at travelers,Greater New York City Area,49,NaN,0.086457