# TF IDF

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
data = pd.read_csv("../data/potential_talents_cleaned.csv")

In [14]:
data.head()

,id,job_title,location,connection,fit,job_title_stem
0,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,2019 c t bauer colleg of busi graduat magna cu...
1,2,native english teacher at epik english progra...,Kanada,500+,NaN,nativ english teacher at epik english program ...
2,3,aspiring hr professional,"Raleigh-Durham, North Carolina Area",44,NaN,aspir hr profession
3,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,peopl develop coordin at ryan
4,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,advisori board member at celal bayar univers

In [15]:
# create a vectorizer 

vectorizer = TfidfVectorizer(ngram_range=(1, 2))
tfidf_matrix = vectorizer.fit_transform(data['job_title'])

In [16]:
# 1 column per candidate, 1 row per unique word

print(tfidf_matrix.shape)

(53, 460)

In [17]:
# display the unique words identified

vectorizer.get_feature_names_out()

array(['2019', '2019 bauer', '2020', '2020 seeking', '2621', '408',
       '408 709', '709', '709 2621', 'about', 'about helping',
       'administration', 'administration at', 'administrative',
       'administrative professionals', 'admissions',
       'admissions representative', 'advisory', 'advisory board',
       'always', 'always set', 'america', 'america groupe', 'an',
       'an energetic', 'an entry', 'an inclusive', 'an internship',
       'analyst', 'analytics', 'analytics at', 'and', 'and analytics',
       'and aspiring', 'and engaging', 'and generalist',
       'and organization', 'and paint', 'and programmer',
       'and recruiting', 'and relocation', 'and team', 'army',
       'army national', 'arts', 'arts major', 'aspiring', 'aspiring hr',
       'assistant', 'assistant at', 'at', 'at celal', 'at chapman',
       'at community', 'at delphi', 'at endemol', 'at epik',
       'at excellence', 'at ey', 'at heil', 'at humber', 'at indiana',
       'at intercontinental', 'at jti', 'at loparex', 'at luxottica',
       'at ryan', 'at schwan', 'at scottmadden', 'at styczynski',
       'at travelers', 'at western', 'at westfield', 'atlanta',
       'bachelor', 'bachelor of', 'bauer', 'bauer college', 'bayar',
       'bayar university', 'beach', 'benefits', 'benefits compensation',
       'beneteau', 'biology', 'biology from', 'board', 'board member',
       'brand', 'brand portfolio', 'buckhead', 'buckhead atlanta',
       'business', 'business graduate', 'business intelligence',
       'business management', 'business partner', 'care', 'celal',
       'celal bayar', 'center', 'center long', 'chapman',
       'chapman university', 'chro', 'chro marketing', 'college',
       'college and', 'college of', 'communications',
       'communications csr', 'community', 'community medical',
       'compensation', 'conflict', 'conflict management', 'coordinator',
       'coordinator at', 'create', 'create an', 'csr', 'csr officer',
       'cum', 'cum laude', 'customer', 'customer service', 'data',
       'data and', 'delphi', 'delphi hardware', 'development',
       'development coordinator', 'director', 'director hr',
       'director of', 'employment', 'employment opportunities', 'endemol',
       'endemol shine', 'energetic', 'energetic and', 'energy',
       'energy gphr', 'engaging', 'engaging work', 'engie',
       'engie houston', 'engineer', 'engineer information', 'english',
       'english program', 'english teacher', 'entry', 'entry level',
       'environment', 'environmental', 'epik', 'epik english',
       'excellence', 'excellence logging', 'executive', 'executive at',
       'experienced', 'experienced retail', 'ey', 'focused',
       'focused leader', 'for', 'for data', 'for success', 'for the',
       'from', 'from victoria', 'generalist', 'generalist at',
       'generalist positions', 'gis', 'gis software', 'gphr', 'gphr sphr',
       'graduate', 'graduate magna', 'graduating', 'graduating may',
       'groupe', 'groupe beneteau', 'guard', 'guard recruiter',
       'hardware', 'hardware and', 'heil', 'heil environmental',
       'helping', 'helping to', 'houston', 'houston the', 'hr',
       'hr analyst', 'hr at', 'hr business', 'hr conflict',
       'hr coordinator', 'hr generalist', 'hr hris', 'hr management',
       'hr manager', 'hr north', 'hr opportunities', 'hr payroll',
       'hr position', 'hr professional', 'hr senior', 'hr specialist',
       'hr staffing', 'hris', 'hris and', 'human', 'human resources',
       'humber', 'humber college', 'illinois', 'illinois university',
       'in', 'in biology', 'in gis', 'in hr', 'in korea', 'in st', 'inc',
       'inclusive', 'inclusive and', 'indiana', 'indiana university',
       'information', 'information systems', 'intelligence',
       'intelligence and', 'intercontinental',
       'intercontinental buckhead', 'international', 'internship',
       'internship in', 'is', 'is seeking', 'japan', 'japan tobacco',
       'jti', 'jti japan', 'junior', 'junior mes', 'kokomo',
       'kokomo business', 'korea', 'lab', 'laude', 'laude and', 'lead',
       'lead official', 'leader', 'leader in', 'level', 'level hr',
       'liberal', 'liberal arts', 'logging', 'long', 'long beach',
       'loparex', 'louis', 'love', 'love for', 'luxottica', 'magna',
       'magna cum', 'major', 'major and', 'major aspiring', 'management',
       'management benefits', 'management major', 'management policies',
       'management retail', 'management student', 'manager',
       'manager and', 'manager at', 'manager graduating',
       'manager seeking', 'marketing', 'marketing communications', 'may',
       'may 2020', 'medical', 'medical center', 'member', 'member at',
       'mes', 'mes engineer', 'national', 'national guard', 'native',
       'native english', 'north', 'north america', 'nortia',
       'nortia staffing', 'of', 'of administration', 'of business',
       'of hr', 'of science', 'of wellington', 'office', 'office manager',
       'officer', 'officer engie', 'official', 'official at', 'open',
       'open to', 'opportunities', 'opportunities open',
       'opportunities within', 'or', 'or patient', 'organization',
       'paint', 'partner', 'partner at', 'passionate', 'passionate about',
       'patient', 'patient care', 'payroll', 'payroll administrative',
       'people', 'people development', 'policies', 'policies procedures',
       'portfolio', 'portfolio executive', 'position', 'position in',
       'positions', 'procedures', 'procedures talent', 'professional',
       'professional an', 'professional for', 'professional passionate',
       'professionals', 'professionals 408', 'program', 'program in',
       'programmer', 'programmer with', 'recruiter', 'recruiter office',
       'recruiting', 'recruiting professional', 'relocation',
       'representative', 'representative at', 'research',
       'research assistant', 'resources', 'resources opportunities',
       'retail', 'retail manager', 'retired', 'retired army', 'rrp',
       'rrp brand', 'ryan', 'schwan', 'science', 'science in',
       'scottmadden', 'scottmadden inc', 'seeking', 'seeking an',
       'seeking employment', 'seeking hr', 'seeking human',
       'seeking internship', 'seeking position', 'senior', 'senior hr',
       'senior specialist', 'service', 'service or', 'set', 'set them',
       'shine', 'shine north', 'software', 'specialist', 'specialist and',
       'specialist at', 'sphr', 'st', 'st louis', 'staffing',
       'staffing and', 'staffing is', 'state', 'state university',
       'student', 'student at', 'student seeking', 'styczynski',
       'styczynski lab', 'success', 'svp', 'svp chro', 'systems',
       'systems specialist', 'talent', 'talent management', 'teacher',
       'teacher at', 'team', 'team focused', 'the', 'the woodlands',
       'the world', 'them', 'them up', 'to', 'to create', 'to travel',
       'tobacco', 'tobacco international', 'travel', 'travel and',
       'travelers', 'undergraduate', 'undergraduate research',
       'university', 'university kokomo', 'university of', 'up', 'up for',
       'victoria', 'victoria university', 'wellington', 'western',
       'western illinois', 'westfield', 'westfield state', 'with',
       'with love', 'within', 'within customer', 'woodlands',
       'woodlands energy', 'work', 'work environment', 'world',
       'world leader'], dtype=object)

In [18]:
# define the job title of the role looking to be filled

target_job = ['aspiring human resources']

In [19]:
# transform this job title using the vectorizer

target_tfidf = vectorizer.transform(target_job)

In [20]:
# calculate the cosine similarities between the candidates and the vacant role title

similarities = cosine_similarity(
    target_tfidf,
    tfidf_matrix,
).flatten()

In [21]:
# add the similarities to the dataframe and sort

data['similarity'] = similarities
data_ranked = data.sort_values(by='similarity', ascending=False).reset_index(drop=True)

data_ranked

,id,job_title,location,connection,fit,job_title_stem,similarity
0,94,seeking human resources opportunities open t...,Amerika Birleşik Devletleri,415,NaN,seek human resourc opportun open to travel and...,0.423557
1,97,aspiring hr professional,"Kokomo, Indiana Area",71,NaN,aspir hr profession,0.133283
2,3,aspiring hr professional,"Raleigh-Durham, North Carolina Area",44,NaN,aspir hr profession,0.133283
3,6,aspiring hr specialist,Greater New York City Area,1,NaN,aspir hr specialist,0.112264
4,72,business management major and aspiring hr manager,"Monroe, Louisiana Area",5,NaN,busi manag major and aspir hr manag,0.061478
5,73,aspiring hr manager seeking internship in hr,"Houston, Texas Area",7,NaN,aspir hr manag seek internship in hr,0.060293
6,66,experienced retail manager and aspiring hr pro...,"Austin, Texas Area",57,NaN,experienc retail manag and aspir hr profession,0.059900
7,27,aspiring hr management student seeking an inte...,"Houston, Texas Area",500+,NaN,aspir hr manag student seek an internship,0.057484
8,79,liberal arts major aspiring hr analyst,"Baton Rouge, Louisiana Area",7,NaN,liber art major aspir hr analyst,0.056782
9,7,student at humber college and aspiring hr gene...,Kanada,61,NaN,student at humber colleg and aspir hr generalist,0.055035
10,82,aspiring hr professional an energetic and te...,"Austin, Texas Area",174,NaN,aspir hr profession an energet and team focus ...,0.047002
11,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,2019 c t bauer colleg of busi graduat magna cu...,0.037347
12,76,aspiring hr professional passionate about he...,"New York, New York",212,NaN,aspir hr profession passion about help to crea...,0.034898
13,100,aspiring hr manager graduating may 2020 se...,"Cape Girardeau, Missouri",103,NaN,aspir hr manag graduat may 2020 seek an entri ...,0.034511
14,98,student,"Houston, Texas Area",4,NaN,student,0.000000
15,90,undergraduate research assistant at styczynski...,Greater Atlanta Area,155,NaN,undergradu research assist at styczynski lab,0.000000
16,85,rrp brand portfolio executive at jti japan to...,Greater Philadelphia Area,500+,NaN,rrp brand portfolio execut at jti japan tobacc...,0.000000
17,86,information systems specialist and programmer ...,"Gaithersburg, Maryland",4,NaN,inform system specialist and programm with a l...,0.000000
18,103,always set them up for success,Greater Los Angeles Area,500+,NaN,alway set them up for success,0.000000
19,87,bachelor of science in biology from victoria u...,"Baltimore, Maryland",40,NaN,bachelor of scienc in biolog from victoria uni...,0.000000
20,88,hr management major,"Milpitas, California",18,NaN,hr manag major,0.000000
21,89,director hr at ey,Greater Atlanta Area,349,NaN,director hr at ey,0.000000
22,102,business intelligence and analytics at travelers,Greater New York City Area,49,NaN,busi intellig and analyt at travel,0.000000
23,96,student at indiana university kokomo busines...,"Lafayette, Indiana",19,NaN,student at indiana univers kokomo busi manag r...,0.000000
24,101,hr generalist at loparex,"Raleigh-Durham, North Carolina Area",500+,NaN,hr generalist at loparex,0.000000
25,91,lead official at western illinois university,Greater Chicago Area,39,NaN,lead offici at western illinoi univers,0.000000
26,92,seeking employment opportunities within custom...,"Torrance, California",64,NaN,seek employ opportun within custom servic or p...,0.000000
27,93,admissions representative at community medical...,"Long Beach, California",9,NaN,admiss repres at commun medic center long beach,0.000000
28,84,hr professional for the world leader in gis so...,"Highland, California",50,NaN,hr profession for the world leader in gi softwar,0.000000
29,99,seeking hr position,"Las Vegas, Nevada Area",48,NaN,seek hr posit,0.000000
30,95,student at westfield state university,"Bridgewater, Massachusetts",57,NaN,student at westfield state univers,0.000000
31,78,hr generalist at schwan s,Amerika Birleşik Devletleri,500+,NaN,hr generalist at schwan s,0.000000
32,83,hr manager at endemol shine north america,"Los Angeles, California",268,NaN,hr manag at endemol shine north america,0.000000
33,67,hr staffing and recruiting professional,"Jackson, Mississippi Area",500+,NaN,hr staf and recruit profession,0.000000
34,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,peopl develop coordin at ryan,0.000000
35,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,advisori board member at celal bayar univers,0.000000
36,8,hr senior specialist,San Francisco Bay Area,500+,NaN,hr senior specialist,0.000000
37,10,seeking hr hris and generalist positions,Greater Philadelphia Area,500+,NaN,seek hr hri and generalist posit,0.000000
38,11,student at chapman university,"Lake Forest, California",2,NaN,student at chapman univers,0.000000
39,12,svp chro marketing communications csr off...,"Houston, Texas Area",500+,NaN,svp chro market commun csr offic engi houston ...,0.000000
40,13,hr coordinator at intercontinental buckhead at...,"Atlanta, Georgia",500+,NaN,hr coordin at intercontinent buckhead atlanta,0.000000
41,28,seeking hr opportunities,"Chicago, Illinois",390,NaN,seek hr opportun,0.000000
42,68,hr specialist at luxottica,Greater New York City Area,500+,NaN,hr specialist at luxottica,0.000000
43,81,senior hr business partner at heil environmental,"Chattanooga, Tennessee Area",455,NaN,senior hr busi partner at heil environment,0.000000
44,69,director of hr north america groupe beneteau,"Greater Grand Rapids, Michigan Area",500+,NaN,director of hr north america group beneteau,0.000000
45,70,retired army national guard recruiter office ...,"Virginia Beach, Virginia",82,NaN,retir armi nation guard recruit offic manag se...,0.000000
46,71,hr generalist at scottmadden inc,"Raleigh-Durham, North Carolina Area",500+,NaN,hr generalist at scottmadden inc,0.000000
47,74,hr professional,Greater Boston Area,16,NaN,hr profession,0.000000
48,75,nortia staffing is seeking hr payroll admin...,"San Jose, California",500+,NaN,nortia staf is seek hr payrol administr profes...,0.000000
49,77,hr \nconflict management \npolicies procedur...,Dallas/Fort Worth Area,409,NaN,hr conflict manag polici procedur talent manag...,0.000000
50,2,native english teacher at epik english progra...,Kanada,500+,NaN,nativ english teacher at epik english program ...,0.000000
51,80,junior mes engineer information systems,"Myrtle Beach, South Carolina Area",52,NaN,junior me engin inform system,0.000000
52,104,director of administration at excellence logging,"Katy, Texas",500+,NaN,director of administr at excel log,0.000000