# TF IDF

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
data = pd.read_csv("../data/potential_talents_cleaned.csv")

In [3]:
data.head()

,id,job_title,location,connection,fit
0,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN
1,2,native english teacher at epik english progra...,Kanada,500+,NaN
2,3,aspiring human resources professional,"Raleigh-Durham, North Carolina Area",44,NaN
3,4,people development coordinator at ryan,"Denton, Texas",500+,NaN
4,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN

In [15]:
# create a vectorizer 

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(data['job_title'])

In [16]:
# 1 column per candidate, 1 row per unique word

print(tfidf_matrix.shape)

(53, 200)

In [17]:
# display the unique words identified

vectorizer.get_feature_names_out()

array(['2019', '2020', '2621', '408', '709', 'about', 'administration',
       'administrative', 'admissions', 'advisory', 'always', 'america',
       'an', 'analyst', 'analytics', 'and', 'army', 'arts', 'aspiring',
       'assistant', 'at', 'atlanta', 'bachelor', 'bauer', 'bayar',
       'beach', 'benefits', 'beneteau', 'biology', 'board', 'brand',
       'buckhead', 'business', 'care', 'celal', 'center', 'chapman',
       'chro', 'college', 'communications', 'community', 'compensation',
       'conflict', 'coordinator', 'create', 'csr', 'cum', 'customer',
       'data', 'delphi', 'development', 'director', 'employment',
       'endemol', 'energetic', 'energy', 'engaging', 'engie', 'engineer',
       'english', 'entry', 'environment', 'environmental', 'epik',
       'excellence', 'executive', 'experienced', 'ey', 'focused', 'for',
       'from', 'generalist', 'gis', 'gphr', 'graduate', 'graduating',
       'groupe', 'guard', 'hardware', 'heil', 'helping', 'houston', 'hr',
       'hris', 'human', 'humber', 'illinois', 'in', 'inc', 'inclusive',
       'indiana', 'information', 'intelligence', 'intercontinental',
       'international', 'internship', 'is', 'japan', 'jti', 'junior',
       'kokomo', 'korea', 'lab', 'laude', 'lead', 'leader', 'level',
       'liberal', 'logging', 'long', 'loparex', 'louis', 'love',
       'luxottica', 'magna', 'major', 'management', 'manager',
       'marketing', 'may', 'medical', 'member', 'mes', 'national',
       'native', 'north', 'nortia', 'of', 'office', 'officer', 'official',
       'open', 'opportunities', 'or', 'organization', 'paint', 'partner',
       'passionate', 'patient', 'payroll', 'people', 'policies',
       'portfolio', 'position', 'positions', 'procedures', 'professional',
       'professionals', 'program', 'programmer', 'recruiter',
       'recruiting', 'relocation', 'representative', 'research',
       'resources', 'retail', 'retired', 'rrp', 'ryan', 'schwan',
       'science', 'scottmadden', 'seeking', 'senior', 'service', 'set',
       'shine', 'software', 'specialist', 'sphr', 'st', 'staffing',
       'state', 'student', 'styczynski', 'success', 'svp', 'systems',
       'talent', 'teacher', 'team', 'the', 'them', 'to', 'tobacco',
       'travel', 'travelers', 'undergraduate', 'university', 'up',
       'victoria', 'wellington', 'western', 'westfield', 'with', 'within',
       'woodlands', 'work', 'world'], dtype=object)

In [18]:
# define the job title of the role looking to be filled

target_job = ['aspiring human resources']

In [19]:
# transform this job title using the vectorizer

target_tfidf = vectorizer.transform(target_job)

In [21]:
# calculate the cosine similarities between the candidates and the vacant role title

similarities = cosine_similarity(
    target_tfidf,
    tfidf_matrix,
).flatten()

In [24]:
# add the similarities to the dataframe and sort

data['similarity'] = similarities
data_ranked = data.sort_values(by='similarity', ascending=False).reset_index(drop=True)

data_ranked

,id,job_title,location,connection,fit,similarity
0,97,aspiring human resources professional,"Kokomo, Indiana Area",71,NaN,0.761756
1,3,aspiring human resources professional,"Raleigh-Durham, North Carolina Area",44,NaN,0.761756
2,6,aspiring human resources specialist,Greater New York City Area,1,NaN,0.682828
3,73,aspiring human resources manager seeking inte...,"Houston, Texas Area",7,NaN,0.576029
4,72,business management major and aspiring human r...,"Monroe, Louisiana Area",5,NaN,0.415676
5,74,human resources professional,Greater Boston Area,16,NaN,0.412834
6,27,aspiring human resources management student se...,"Houston, Texas Area",500+,NaN,0.398810
7,66,experienced retail manager and aspiring human ...,"Austin, Texas Area",57,NaN,0.391409
8,7,student at humber college and aspiring human r...,Kanada,61,NaN,0.370897
9,79,liberal arts major aspiring human resources a...,"Baton Rouge, Louisiana Area",7,NaN,0.356918
10,100,aspiring human resources manager graduating ...,"Cape Girardeau, Missouri",103,NaN,0.321987
11,82,aspiring human resources professional an ene...,"Austin, Texas Area",174,NaN,0.308270
12,99,seeking human resources position,"Las Vegas, Nevada Area",48,NaN,0.287013
13,28,seeking human resources opportunities,"Chicago, Illinois",390,NaN,0.287013
14,88,human resources management major,"Milpitas, California",18,NaN,0.268190
15,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,0.241850
16,101,human resources generalist at loparex,"Raleigh-Durham, North Carolina Area",500+,NaN,0.232708
17,78,human resources generalist at schwan s,Amerika Birleşik Devletleri,500+,NaN,0.232708
18,68,human resources specialist at luxottica,Greater New York City Area,500+,NaN,0.229000
19,76,aspiring human resources professional passio...,"New York, New York",212,NaN,0.224897
20,89,director human resources at ey,Greater Atlanta Area,349,NaN,0.224437
21,67,human resources staffing and recruiting profe...,"Jackson, Mississippi Area",500+,NaN,0.197231
22,71,human resources generalist at scottmadden inc,"Raleigh-Durham, North Carolina Area",500+,NaN,0.189854
23,10,seeking human resources hris and generalist po...,Greater Philadelphia Area,500+,NaN,0.176059
24,13,human resources coordinator at intercontinenta...,"Atlanta, Georgia",500+,NaN,0.159131
25,81,senior human resources business partner at hei...,"Chattanooga, Tennessee Area",455,NaN,0.149690
26,69,director of human resources north america gro...,"Greater Grand Rapids, Michigan Area",500+,NaN,0.143923
27,94,seeking human resources opportunities open t...,Amerika Birleşik Devletleri,415,NaN,0.140674
28,84,human resources professional for the world lea...,"Highland, California",50,NaN,0.128997
29,70,retired army national guard recruiter office ...,"Virginia Beach, Virginia",82,NaN,0.114174
30,77,human resources \nconflict management \npolici...,Dallas/Fort Worth Area,409,NaN,0.112897
31,75,nortia staffing is seeking human resources pa...,"San Jose, California",500+,NaN,0.106941
32,102,business intelligence and analytics at travelers,Greater New York City Area,49,NaN,0.000000
33,93,admissions representative at community medical...,"Long Beach, California",9,NaN,0.000000
34,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,0.000000
35,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,0.000000
36,8,hr senior specialist,San Francisco Bay Area,500+,NaN,0.000000
37,98,student,"Houston, Texas Area",4,NaN,0.000000
38,103,always set them up for success,Greater Los Angeles Area,500+,NaN,0.000000
39,96,student at indiana university kokomo busines...,"Lafayette, Indiana",19,NaN,0.000000
40,95,student at westfield state university,"Bridgewater, Massachusetts",57,NaN,0.000000
41,87,bachelor of science in biology from victoria u...,"Baltimore, Maryland",40,NaN,0.000000
42,92,seeking employment opportunities within custom...,"Torrance, California",64,NaN,0.000000
43,91,lead official at western illinois university,Greater Chicago Area,39,NaN,0.000000
44,90,undergraduate research assistant at styczynski...,Greater Atlanta Area,155,NaN,0.000000
45,11,student at chapman university,"Lake Forest, California",2,NaN,0.000000
46,86,information systems specialist and programmer ...,"Gaithersburg, Maryland",4,NaN,0.000000
47,85,rrp brand portfolio executive at jti japan to...,Greater Philadelphia Area,500+,NaN,0.000000
48,83,hr manager at endemol shine north america,"Los Angeles, California",268,NaN,0.000000
49,12,svp chro marketing communications csr off...,"Houston, Texas Area",500+,NaN,0.000000
50,80,junior mes engineer information systems,"Myrtle Beach, South Carolina Area",52,NaN,0.000000
51,2,native english teacher at epik english progra...,Kanada,500+,NaN,0.000000
52,104,director of administration at excellence logging,"Katy, Texas",500+,NaN,0.000000