# TF IDF

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.stem import PorterStemmer

In [13]:
data = pd.read_csv("../data/potential_talents_cleaned.csv")

In [14]:
data.head()

,id,job_title,location,connection,fit,job_title_stem
0,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,2019 c t bauer colleg of busi graduat magna cu...
1,2,native english teacher at epik english progra...,Kanada,500+,NaN,nativ english teacher at epik english program ...
2,3,aspiring hr professional,"Raleigh-Durham, North Carolina Area",44,NaN,aspir hr profession
3,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,peopl develop coordin at ryan
4,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,advisori board member at celal bayar univers

In [29]:
# create a vectorizer from stemmed job titles

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(data['job_title_stem'])

In [30]:
# 1 column per candidate, 1 row per unique word

print(tfidf_matrix.shape)

(53, 191)

In [31]:
# display the unique words identified

vectorizer.get_feature_names_out()

array(['2019', '2020', '2621', '408', '709', 'about', 'administr',
       'admiss', 'advisori', 'alway', 'america', 'an', 'analyst',
       'analyt', 'and', 'armi', 'art', 'aspir', 'assist', 'at', 'atlanta',
       'bachelor', 'bauer', 'bayar', 'beach', 'benefit', 'beneteau',
       'biolog', 'board', 'brand', 'buckhead', 'busi', 'care', 'celal',
       'center', 'chapman', 'chro', 'colleg', 'commun', 'compens',
       'conflict', 'coordin', 'creat', 'csr', 'cum', 'custom', 'data',
       'delphi', 'develop', 'director', 'employ', 'endemol', 'energet',
       'energi', 'engag', 'engi', 'engin', 'english', 'entri', 'environ',
       'environment', 'epik', 'excel', 'execut', 'experienc', 'ey',
       'focus', 'for', 'from', 'generalist', 'gi', 'gphr', 'graduat',
       'group', 'guard', 'hardwar', 'heil', 'help', 'houston', 'hr',
       'hri', 'human', 'humber', 'illinoi', 'in', 'inc', 'inclus',
       'indiana', 'inform', 'intellig', 'intercontinent', 'intern',
       'internship', 'is', 'japan', 'jti', 'junior', 'kokomo', 'korea',
       'lab', 'laud', 'lead', 'leader', 'level', 'liber', 'log', 'long',
       'loparex', 'loui', 'love', 'luxottica', 'magna', 'major', 'manag',
       'market', 'may', 'me', 'medic', 'member', 'nation', 'nativ',
       'north', 'nortia', 'of', 'offic', 'offici', 'open', 'opportun',
       'or', 'organ', 'paint', 'partner', 'passion', 'patient', 'payrol',
       'peopl', 'polici', 'portfolio', 'posit', 'procedur', 'profession',
       'program', 'programm', 'recruit', 'reloc', 'repres', 'research',
       'resourc', 'retail', 'retir', 'rrp', 'ryan', 'schwan', 'scienc',
       'scottmadden', 'seek', 'senior', 'servic', 'set', 'shine',
       'softwar', 'specialist', 'sphr', 'st', 'staf', 'state', 'student',
       'styczynski', 'success', 'svp', 'system', 'talent', 'teacher',
       'team', 'the', 'them', 'to', 'tobacco', 'travel', 'undergradu',
       'univers', 'up', 'victoria', 'wellington', 'western', 'westfield',
       'with', 'within', 'woodland', 'work', 'world'], dtype=object)

In [40]:
# define the job title of the role looking to be filled
stemmer = PorterStemmer()
target_job = 'aspiring hr'
target_stem = ' '.join(
    stemmer.stem(word)
    for word in target_job.split()
)
target_stem

'aspir hr'

In [45]:
# transform this job title using the vectorizer

target_tfidf = vectorizer.transform([target_stem])

In [46]:
# calculate the cosine similarities between the candidates and the vacant role title

similarities = cosine_similarity(
    target_tfidf,
    tfidf_matrix,
).flatten()

In [47]:
# add the similarities to the dataframe and sort

data['similarity'] = similarities
data_ranked = data.sort_values(by='similarity', ascending=False).reset_index(drop=True)

data_ranked

,id,job_title,location,connection,fit,job_title_stem,similarity
0,97,aspiring hr professional,"Kokomo, Indiana Area",71,NaN,aspir hr profession,0.730043
1,3,aspiring hr professional,"Raleigh-Durham, North Carolina Area",44,NaN,aspir hr profession,0.730043
2,6,aspiring hr specialist,Greater New York City Area,1,NaN,aspir hr specialist,0.633628
3,73,aspiring hr manager seeking internship in hr,"Houston, Texas Area",7,NaN,aspir hr manag seek internship in hr,0.491485
4,27,aspiring hr management student seeking an inte...,"Houston, Texas Area",500+,NaN,aspir hr manag student seek an internship,0.366925
5,66,experienced retail manager and aspiring hr pro...,"Austin, Texas Area",57,NaN,experienc retail manag and aspir hr profession,0.355699
6,72,business management major and aspiring hr manager,"Monroe, Louisiana Area",5,NaN,busi manag major and aspir hr manag,0.347094
7,7,student at humber college and aspiring hr gene...,Kanada,61,NaN,student at humber colleg and aspir hr generalist,0.330332
8,79,liberal arts major aspiring hr analyst,"Baton Rouge, Louisiana Area",7,NaN,liber art major aspir hr analyst,0.317496
9,82,aspiring hr professional an energetic and te...,"Austin, Texas Area",174,NaN,aspir hr profession an energet and team focus ...,0.273837
10,100,aspiring hr manager graduating may 2020 se...,"Cape Girardeau, Missouri",103,NaN,aspir hr manag graduat may 2020 seek an entri ...,0.259995
11,74,hr professional,Greater Boston Area,16,NaN,hr profession,0.259756
12,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,2019 c t bauer colleg of busi graduat magna cu...,0.215852
13,76,aspiring hr professional passionate about he...,"New York, New York",212,NaN,aspir hr profession passion about help to crea...,0.198500
14,99,seeking hr position,"Las Vegas, Nevada Area",48,NaN,seek hr posit,0.171647
15,88,hr management major,"Milpitas, California",18,NaN,hr manag major,0.165409
16,28,seeking hr opportunities,"Chicago, Illinois",390,NaN,seek hr opportun,0.165409
17,8,hr senior specialist,San Francisco Bay Area,500+,NaN,hr senior specialist,0.144279
18,101,hr generalist at loparex,"Raleigh-Durham, North Carolina Area",500+,NaN,hr generalist at loparex,0.131740
19,78,hr generalist at schwan s,Amerika Birleşik Devletleri,500+,NaN,hr generalist at schwan s,0.131740
20,68,hr specialist at luxottica,Greater New York City Area,500+,NaN,hr specialist at luxottica,0.129504
21,89,director hr at ey,Greater Atlanta Area,349,NaN,director hr at ey,0.126761
22,67,hr staffing and recruiting professional,"Jackson, Mississippi Area",500+,NaN,hr staf and recruit profession,0.115215
23,71,hr generalist at scottmadden inc,"Raleigh-Durham, North Carolina Area",500+,NaN,hr generalist at scottmadden inc,0.106291
24,10,seeking hr hris and generalist positions,Greater Philadelphia Area,500+,NaN,seek hr hri and generalist posit,0.104379
25,13,hr coordinator at intercontinental buckhead at...,"Atlanta, Georgia",500+,NaN,hr coordin at intercontinent buckhead atlanta,0.088516
26,83,hr manager at endemol shine north america,"Los Angeles, California",268,NaN,hr manag at endemol shine north america,0.086609
27,81,senior hr business partner at heil environmental,"Chattanooga, Tennessee Area",455,NaN,senior hr busi partner at heil environment,0.083119
28,69,director of hr north america groupe beneteau,"Greater Grand Rapids, Michigan Area",500+,NaN,director of hr north america group beneteau,0.079836
29,84,hr professional for the world leader in gis so...,"Highland, California",50,NaN,hr profession for the world leader in gi softwar,0.071537
30,77,hr \nconflict management \npolicies procedur...,Dallas/Fort Worth Area,409,NaN,hr conflict manag polici procedur talent manag...,0.065386
31,70,retired army national guard recruiter office ...,"Virginia Beach, Virginia",82,NaN,retir armi nation guard recruit offic manag se...,0.065242
32,75,nortia staffing is seeking hr payroll admin...,"San Jose, California",500+,NaN,nortia staf is seek hr payrol administr profes...,0.061769
33,103,always set them up for success,Greater Los Angeles Area,500+,NaN,alway set them up for success,0.000000
34,102,business intelligence and analytics at travelers,Greater New York City Area,49,NaN,busi intellig and analyt at travel,0.000000
35,94,seeking human resources opportunities open t...,Amerika Birleşik Devletleri,415,NaN,seek human resourc opportun open to travel and...,0.000000
36,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,peopl develop coordin at ryan,0.000000
37,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,advisori board member at celal bayar univers,0.000000
38,98,student,"Houston, Texas Area",4,NaN,student,0.000000
39,11,student at chapman university,"Lake Forest, California",2,NaN,student at chapman univers,0.000000
40,96,student at indiana university kokomo busines...,"Lafayette, Indiana",19,NaN,student at indiana univers kokomo busi manag r...,0.000000
41,95,student at westfield state university,"Bridgewater, Massachusetts",57,NaN,student at westfield state univers,0.000000
42,12,svp chro marketing communications csr off...,"Houston, Texas Area",500+,NaN,svp chro market commun csr offic engi houston ...,0.000000
43,93,admissions representative at community medical...,"Long Beach, California",9,NaN,admiss repres at commun medic center long beach,0.000000
44,92,seeking employment opportunities within custom...,"Torrance, California",64,NaN,seek employ opportun within custom servic or p...,0.000000
45,91,lead official at western illinois university,Greater Chicago Area,39,NaN,lead offici at western illinoi univers,0.000000
46,90,undergraduate research assistant at styczynski...,Greater Atlanta Area,155,NaN,undergradu research assist at styczynski lab,0.000000
47,87,bachelor of science in biology from victoria u...,"Baltimore, Maryland",40,NaN,bachelor of scienc in biolog from victoria uni...,0.000000
48,86,information systems specialist and programmer ...,"Gaithersburg, Maryland",4,NaN,inform system specialist and programm with a l...,0.000000
49,85,rrp brand portfolio executive at jti japan to...,Greater Philadelphia Area,500+,NaN,rrp brand portfolio execut at jti japan tobacc...,0.000000
50,80,junior mes engineer information systems,"Myrtle Beach, South Carolina Area",52,NaN,junior me engin inform system,0.000000
51,2,native english teacher at epik english progra...,Kanada,500+,NaN,nativ english teacher at epik english program ...,0.000000
52,104,director of administration at excellence logging,"Katy, Texas",500+,NaN,director of administr at excel log,0.000000